export const DEFAULT_EMAIL_TEMPLATES: Record<string, { subject: string; bodyHtml: string }> = {
  'email-verification-code': {
    subject: 'Verify your email',
    bodyHtml:
      '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Verify Email</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Verify Email</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Enter the following code to verify your email address:</p><h1 style="text-align: center;">%TOKEN%</h1><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn\'t request this, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %APP_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>',
  },
  'email-verification-link': {
    subject: 'Verify your email',
    bodyHtml:
      '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Verify Email</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Verify Email</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Click the button below to verify your email address:</p><div style="text-align: center; margin: 32px 0;"><a href="%LINK%" style="display:inline-block;background:#111827;color:#ffffff;text-decoration:none;padding:12px 32px;border-radius:6px;font-size:14px;font-weight:500;">Verify Email</a></div><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn\'t request this, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %APP_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>',
  },
  'reset-password-code': {
    subject: 'Reset your password',
    bodyHtml:
      '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Reset Password</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Reset Password</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Enter the following code to reset your password:</p><h1 style="text-align: center;">%TOKEN%</h1><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn\'t request a password reset, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %APP_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>',
  },
  'reset-password-link': {
    subject: 'Reset your password',
    bodyHtml:
      '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Reset Password</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Reset Password</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Click the button below to reset your password:</p><div style="text-align: center; margin: 32px 0;"><a href="%LINK%" style="display:inline-block;background:#111827;color:#ffffff;text-decoration:none;padding:12px 32px;border-radius:6px;font-size:14px;font-weight:500;">Reset Password</a></div><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn\'t request a password reset, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %APP_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>',
  },
  'email-address-change-code': {
    subject: 'Verify your new email address',
    bodyHtml:
      '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Email Address Change</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Verify New Email</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Enter the following code to verify your new email address:</p><h1 style="text-align: center;">%TOKEN%</h1><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn\'t request this change, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %APP_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>',
  },
  'email-address-change-link': {
    subject: 'Verify your new email address',
    bodyHtml:
      '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Email Address Change</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Verify New Email</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Click the button below to verify your new email address:</p><div style="text-align: center; margin: 32px 0;"><a href="%LINK%" style="display:inline-block;background:#111827;color:#ffffff;text-decoration:none;padding:12px 32px;border-radius:6px;font-size:14px;font-weight:500;">Verify Email</a></div><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn\'t request this change, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %APP_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>',
  },
};
