openapi: 3.0.3
info:
  title: Insforge Tables API
  version: 1.0.0

paths:
  /api/tables/field-types:
    get:
      summary: Get Available Field Types
      security:
        - bearerAuth: []
        - apiKey: []
      responses:
        '200':
          description: List of available field types with SQL type mappings
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    sqlType:
                      type: string
                    defaultValue:
                      type: string
              example:
                string:
                  sqlType: TEXT
                  defaultValue: "''"
                integer:
                  sqlType: INTEGER
                  defaultValue: "0"
                uuid:
                  sqlType: TEXT
                  defaultValue: gen_random_uuid()
                boolean:
                  sqlType: BOOLEAN
                  defaultValue: "false"
                datetime:
                  sqlType: TIMESTAMPTZ
                  defaultValue: "CURRENT_TIMESTAMP"
                json:
                  sqlType: JSONB
                  defaultValue: "'{}'"
                float:
                  sqlType: REAL
                  defaultValue: "0.0"
                file:
                  sqlType: TEXT
                  defaultValue: "null"

  /api/tables:
    get:
      summary: List Tables
      security:
        - bearerAuth: []
        - apiKey: []
      responses:
        '200':
          description: List of table names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - "users"
                - "posts"
                - "comments"
                - "categories"

    post:
      summary: Create Table
      security:
        - bearerAuth: []
        - apiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tableName
                - columns
              properties:
                tableName:
                  type: string
                columns:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - type
                      - nullable
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                        enum: [string, datetime, integer, float, boolean, uuid, json, file]
                      nullable:
                        type: boolean
                      unique:
                        type: boolean
                      defaultValue:
                        type: string
                      foreignKey:
                        type: object
                        properties:
                          table:
                            type: string
                          column:
                            type: string
                          onDelete:
                            type: string
                            enum: [CASCADE, SET NULL, NO ACTION, RESTRICT]
                            default: NO ACTION
      responses:
        '201':
          description: Table created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  table_name:
                    type: string
              example:
                message: "Table created successfully"
                tableName: "posts"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "VALIDATION_ERROR"
                message: "Table name already exists"
                statusCode: 400
                nextActions: "Choose a different table name"
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "INVALID_FIELD_TYPE"
                message: "Invalid field type: 'text'. Valid types are: string, integer, float, boolean, datetime, uuid, json, file"
                statusCode: 422
                nextActions: "Use one of the valid field types"

  /api/tables/{tableName}/schema:
    get:
      summary: Get Table Schema
      security:
        - bearerAuth: []
        - apiKey: []
      parameters:
        - name: tableName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Table schema
          content:
            application/json:
              schema:
                type: object
                properties:
                  table_name:
                    type: string
                  columns:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                        nullable:
                          type: boolean
                        unique:
                          type: boolean
                        default:
                          type: string
                          nullable: true
                        isPrimaryKey:
                          type: boolean
                        foreignKey:
                          type: object
                          nullable: true
                          properties:
                            table:
                              type: string
                            column:
                              type: string
                            on_delete:
                              type: string
              example:
                tableName: "posts"
                columns:
                  - name: "id"
                    type: "uuid"
                    nullable: false
                    unique: true
                    default: "gen_random_uuid()"
                    isPrimaryKey: true
                    foreignKey: null
                  - name: "title"
                    type: "string"
                    nullable: false
                    unique: false
                    default: null
                    isPrimaryKey: false
                    foreignKey: null
                  - name: "userId"
                    type: "uuid"
                    nullable: false
                    unique: false
                    default: null
                    isPrimaryKey: false
                    foreignKey:
                      table: "users"
                      column: "id"
                      on_delete: "CASCADE"
        '404':
          description: Table not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "TABLE_NOT_FOUND"
                message: "Table 'nonexistent' does not exist"
                statusCode: 404
                nextActions: "Check table name and try again"
    patch:
      summary: Update Table Schema
      security:
        - bearerAuth: []
        - apiKey: []
      parameters:
        - name: tableName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                addColumns:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                      nullable:
                        type: boolean
                      defaultValue:
                        type: string
                dropColumns:
                  type: array
                  items:
                    type: string
                renameColumns:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: Table modified
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  table_name:
                    type: string
                  modifications:
                    type: object
                    properties:
                      addedColumns:
                        type: array
                        items:
                          type: string
                      droppedColumns:
                        type: array
                        items:
                          type: string
                      renamedColumns:
                        type: object
                        additionalProperties:
                          type: string
              example:
                message: "Table modified successfully"
                tableName: "posts"
                modifications:
                  addedColumns: ["published_at"]
                  droppedColumns: ["draft"]
                  renamedColumns:
                    content: "body"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "COLUMN_EXISTS"
                message: "Column 'title' already exists in table 'posts'"
                statusCode: 400
                nextActions: "Choose a different column name or drop it first"

  /api/tables/{tableName}:
    delete:
      summary: Delete Table
      security:
        - bearerAuth: []
        - apiKey: []
      parameters:
        - name: tableName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Table deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  table_name:
                    type: string
              example:
                message: "Table deleted successfully"
                tableName: "posts"
        '404':
          description: Table not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "TABLE_NOT_FOUND"
                message: "Table 'nonexistent' does not exist"
                statusCode: 404
                nextActions: "Check table name and try again"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
  
  schemas:
    ErrorResponse:
      type: object
      required:
        - error
        - message
        - statusCode
      properties:
        error:
          type: string
          description: Error code for programmatic handling
        message:
          type: string
          description: Human-readable error message
        statusCode:
          type: integer
          description: HTTP status code
        nextActions:
          type: string
          description: Suggested action to resolve the error