import type { ColumnIR, CompositeTypeIR, FunctionIR, SchemaIR, TableIR } from './types.js';

const HEADER = `// Generated by @insforge/gen-types. Do not edit by hand.
// Re-run \`insforge-gen-types\` after any schema change.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];
`;

/** Quote an object key only when it is not a plain identifier. */
function key(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function sorted<T>(items: T[], by: (item: T) => string): T[] {
  return [...items].sort((a, b) => by(a).localeCompare(by(b)));
}

function rowField(c: ColumnIR): string {
  return `${key(c.name)}: ${c.tsType}${c.nullable ? ' | null' : ''}`;
}

function insertField(c: ColumnIR): string {
  const optional = c.hasDefault || c.nullable;
  return `${key(c.name)}${optional ? '?' : ''}: ${c.tsType}${c.nullable ? ' | null' : ''}`;
}

function updateField(c: ColumnIR): string {
  return `${key(c.name)}?: ${c.tsType}${c.nullable ? ' | null' : ''}`;
}

function relationships(table: TableIR, indent: string): string {
  if (table.relationships.length === 0) {
    return `${indent}Relationships: []`;
  }
  const rels = sorted(table.relationships, (r) => r.foreignKeyName).map((r) => {
    return (
      `${indent}  {\n` +
      `${indent}    foreignKeyName: ${JSON.stringify(r.foreignKeyName)}\n` +
      `${indent}    columns: ${JSON.stringify(r.columns)}\n` +
      `${indent}    referencedRelation: ${JSON.stringify(r.referencedRelation)}\n` +
      `${indent}    referencedColumns: ${JSON.stringify(r.referencedColumns)}\n` +
      `${indent}  }`
    );
  });
  return `${indent}Relationships: [\n${rels.join(',\n')}\n${indent}]`;
}

function tableBlock(table: TableIR, indent: string): string {
  const cols = sorted(table.columns, (c) => c.name);
  const i = `${indent}  `;
  const block = (label: string, render: (c: ColumnIR) => string) =>
    `${i}${label}: {\n${cols.map((c) => `${i}  ${render(c)}`).join('\n')}\n${i}}`;
  const parts = [block('Row', rowField)];
  // Non-writable views expose a Row only; Insert/Update would be invalid.
  if (table.writable) {
    parts.push(block('Insert', insertField), block('Update', updateField));
  }
  parts.push(relationships(table, i));
  return `${indent}${key(table.name)}: {\n${parts.join('\n')}\n${indent}}`;
}

function group(label: string, tables: TableIR[], indent: string): string {
  if (tables.length === 0) {
    return `${indent}${label}: {}`;
  }
  const blocks = sorted(tables, (t) => t.name).map((t) => tableBlock(t, `${indent}  `));
  return `${indent}${label}: {\n${blocks.join('\n')}\n${indent}}`;
}

function enumsBlock(enums: Record<string, string[]>, indent: string): string {
  const names = Object.keys(enums).sort();
  if (names.length === 0) {
    return `${indent}Enums: {}`;
  }
  const lines = names.map(
    (n) => `${indent}  ${key(n)}: ${enums[n].map((v) => JSON.stringify(v)).join(' | ')}`
  );
  return `${indent}Enums: {\n${lines.join('\n')}\n${indent}}`;
}

function functionBlock(fn: FunctionIR, indent: string): string {
  const i = `${indent}  `;
  const args =
    fn.args.length === 0
      ? `${i}Args: Record<PropertyKey, never>`
      : `${i}Args: {\n${sorted(fn.args, (a) => a.name)
          .map((a) => `${i}  ${key(a.name)}: ${a.tsType}`)
          .join('\n')}\n${i}}`;
  return `${indent}${key(fn.name)}: {\n${args}\n${i}Returns: ${fn.returns}\n${indent}}`;
}

function functionsBlock(functions: FunctionIR[], indent: string): string {
  if (functions.length === 0) {
    return `${indent}Functions: {}`;
  }
  const blocks = sorted(functions, (f) => f.name).map((f) => functionBlock(f, `${indent}  `));
  return `${indent}Functions: {\n${blocks.join('\n')}\n${indent}}`;
}

function compositeTypesBlock(composites: CompositeTypeIR[], indent: string): string {
  if (composites.length === 0) {
    return `${indent}CompositeTypes: {}`;
  }
  const i = `${indent}  `;
  const blocks = sorted(composites, (c) => c.name).map((c) => {
    const fields = sorted(c.fields, (f) => f.name)
      .map((f) => `${i}  ${key(f.name)}: ${f.tsType}${f.nullable ? ' | null' : ''}`)
      .join('\n');
    return `${i}${key(c.name)}: {\n${fields}\n${i}}`;
  });
  return `${indent}CompositeTypes: {\n${blocks.join('\n')}\n${indent}}`;
}

function schemaBlock(schema: SchemaIR): string {
  const parts = [
    group('Tables', schema.tables, '    '),
    group('Views', schema.views, '    '),
    functionsBlock(schema.functions, '    '),
    enumsBlock(schema.enums, '    '),
    compositeTypesBlock(schema.compositeTypes, '    '),
  ];
  return `  ${key(schema.name)}: {\n${parts.join('\n')}\n  }`;
}

/** Render the introspected schemas into a deterministic TypeScript module. */
export function format(schemas: SchemaIR[]): string {
  const blocks = sorted(schemas, (s) => s.name).map(schemaBlock);
  return `${HEADER}\nexport interface Database {\n${blocks.join('\n')}\n}\n`;
}
