-- Migration: Update all default email templates to the official CloudMove clean layout

-- 1. email-verification-code
UPDATE email.templates SET body_html = '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Email Verification</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, ''Helvetica Neue'', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Verification Code</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Thank you for signing up! Enter the following code when prompted:</p><h1 style="text-align: center;">%TOKEN%</h1><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn''t create an account, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %DISPLAY_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>'
WHERE template_type = 'email-verification-code';

-- 2. email-verification-link
UPDATE email.templates SET body_html = '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Email Verification</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, ''Helvetica Neue'', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Verify Your Email</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Thank you for signing up! Click the button below to verify your email address:</p><div style="text-align: center; margin: 32px 0;"><a href="%LINK%" style="display:inline-block;background:#111827;color:#ffffff;text-decoration:none;padding:12px 32px;border-radius:6px;font-size:14px;font-weight:500;">Verify Email</a></div><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn''t create an account, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %DISPLAY_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>'
WHERE template_type = 'email-verification-link';

-- 3. reset-password-code
UPDATE email.templates SET body_html = '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Reset Password</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, ''Helvetica Neue'', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Reset Password</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Enter the following code to reset your password:</p><h1 style="text-align: center;">%TOKEN%</h1><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn''t request a password reset, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %DISPLAY_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>'
WHERE template_type = 'reset-password-code';

-- 4. reset-password-link
UPDATE email.templates SET body_html = '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Reset Password</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, ''Helvetica Neue'', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Reset Password</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Click the button below to reset your password:</p><div style="text-align: center; margin: 32px 0;"><a href="%LINK%" style="display:inline-block;background:#111827;color:#ffffff;text-decoration:none;padding:12px 32px;border-radius:6px;font-size:14px;font-weight:500;">Reset Password</a></div><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn''t request a password reset, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %DISPLAY_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>'
WHERE template_type = 'reset-password-link';

-- 5. email-address-change-code
UPDATE email.templates SET body_html = '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Email Address Change</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, ''Helvetica Neue'', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Verify New Email</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Enter the following code to verify your new email address:</p><h1 style="text-align: center;">%TOKEN%</h1><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn''t request this change, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %DISPLAY_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>'
WHERE template_type = 'email-address-change-code';

-- 6. email-address-change-link
UPDATE email.templates SET body_html = '<!DOCTYPE html><html><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Email Address Change</title></head><body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, ''Helvetica Neue'', Arial, sans-serif;"><table role="presentation" style="width: 100%; border-collapse: collapse;"><tr><td align="center" style="padding: 40px 20px;"><table role="presentation" style="max-width: 520px; width: 100%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px;"><tr><td style="padding: 0 24px 48px 24px;"><h1 style="margin: 0 0 24px 0; font-size: 32px; font-weight: 500; color: #000; text-align: left; line-height: 1.2;">Verify New Email</h1><p style="margin: 0 0 8px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">Click the button below to verify your new email address:</p><div style="text-align: center; margin: 32px 0;"><a href="%LINK%" style="display:inline-block;background:#111827;color:#ffffff;text-decoration:none;padding:12px 32px;border-radius:6px;font-size:14px;font-weight:500;">Verify Email</a></div><p style="margin: 0 0 24px 0; font-size: 16px; color: #000000; text-align: left; line-height: 1.5;">If you didn''t request this change, you can safely ignore this email.</p></td></tr></table><div class="footer" style="max-width: 600px; width: 100%; border-collapse: collapse; margin-top: 16px; text-align: center; color: #666; font-size: 14px;"><p>Sent by %DISPLAY_NAME%, Secured by <a href="https://insforge.dev" style="color: #666;">InsForge</a>.</p></div></td></tr></table></body></html>'
WHERE template_type = 'email-address-change-link';
